import logging

from mcp.server.fastmcp import FastMCP

# Model loading lives in the spaCy Singleton manager (loaded once per process,
# NER excluded, thread-safe). SPACY_MODELS is re-exported here for backward
# compatibility — this module remains the documented home of the mapping.
from mcp_servers.spacy_manager import SPACY_MODELS, get_model

logger = logging.getLogger(__name__)

# Initialize FastMCP server
mcp = FastMCP('LinguisticsServer')

# --- Curated high-risk false friends -----------------------------------------
# Maps an L1 word (lowercased) -> target language -> the twin scenario pair:
#   * false_friend: the L2 word that looks/sounds alike but means something else
#   * true_meaning: the correct semantic translation in the L2
# This is the ONLY thing the local server is authoritative about. Secondary
# "similar options" are deliberately NOT computed here — a local edit-distance
# scan produces irrelevant noise (e.g. 'realize' for 'peixe'); that intelligence
# now lives in the LLM layer (see the orchestrator's Pedagogue call).
CONTRASTIVE_DB = {
    "pretender": {
        "English": {
            "false_friend": {"word": "pretend", "meaning": "to fake or act as if something is true"},
            "true_meaning": {"word": "intend", "meaning": "to plan or aim to do something"},
        },
    },
    "puxar": {
        "English": {
            "false_friend": {"word": "push", "meaning": "to press something away from you"},
            "true_meaning": {"word": "pull", "meaning": "to draw something toward you"},
        },
    },
    "parentes": {
        "English": {
            "false_friend": {"word": "parents", "meaning": "one's mother and father"},
            "true_meaning": {"word": "relatives", "meaning": "family members in general"},
        },
    },
    "livraria": {
        "English": {
            "false_friend": {"word": "library", "meaning": "a place where you borrow books"},
            "true_meaning": {"word": "bookstore", "meaning": "a shop that sells books"},
        },
    },
    "colegio": {
        "English": {
            "false_friend": {"word": "college", "meaning": "higher education after high school"},
            "true_meaning": {"word": "school", "meaning": "a place for primary or secondary education"},
        },
    },
    "eventualmente": {
        "English": {
            "false_friend": {"word": "eventually", "meaning": "in the end, after some time"},
            "true_meaning": {"word": "occasionally", "meaning": "from time to time"},
        },
    },
    "realizar": {
        "English": {
            "false_friend": {"word": "realize", "meaning": "to become aware of something"},
            "true_meaning": {"word": "accomplish", "meaning": "to carry out or achieve something"},
        },
    },
    "assistir": {
        "English": {
            "false_friend": {"word": "assist", "meaning": "to help someone"},
            "true_meaning": {"word": "attend", "meaning": "to watch or be present at something"},
        },
    },
}


@mcp.tool()
def discover_contrastive_scenarios(word_l1: str, l2_lang: str = "English") -> dict:
    """
    Look up the curated twin contrastive scenarios for a single L1 word.

    Given a native-language (L1) word and a target language (L2), this checks the
    curated false-friend knowledge base and returns a clean payload telling the
    orchestrator whether authoritative local data exists:
      * dangerous: the false-friend L2 word (looks alike, different meaning) or None
      * safe: the true semantic translation in the L2, or None
      * has_local_data: True if the word is a known high-risk false friend
      * needs_dynamic_suggestions: always True — the "similar options" list is
        generated by the LLM layer, never by a local character-matching scan

    Args:
        word_l1: The native-language word to analyze.
        l2_lang: The target language to compare against.

    Returns:
        A dict with keys: l1_word, l2_lang, dangerous, safe, has_local_data,
        needs_dynamic_suggestions, warning.
    """
    w = word_l1.lower().strip()
    result = {
        "l1_word": word_l1.strip(),
        "l2_lang": l2_lang,
        "dangerous": None,
        "safe": None,
        "has_local_data": False,
        "needs_dynamic_suggestions": True,
        "warning": None,
    }

    if not w:
        result["warning"] = "Input word cannot be empty."
        return result

    entry = CONTRASTIVE_DB.get(w, {}).get(l2_lang)
    if entry:
        result["dangerous"] = dict(entry["false_friend"])
        result["safe"] = dict(entry["true_meaning"])
        result["has_local_data"] = True
    else:
        result["warning"] = (
            f"No curated false-friend data for '{word_l1}' in {l2_lang}; "
            "secondary suggestions will be generated dynamically by the LLM."
        )

    logger.info("mcp.discover", extra={"tool": "discover_contrastive_scenarios",
                "l2": l2_lang, "has_local_data": result["has_local_data"]})
    return result


def _scan_false_friends(tokens: list, l2_lang: str) -> list:
    """Raw dictionary lookup of each token against CONTRASTIVE_DB — no spaCy needed.

    Returns the curated twin scenarios for any known false friend found in the tokens."""
    found = []
    seen = set()
    for token in tokens:
        key = str(token).lower().strip(".,;:!?\"'()[]«»…")
        if not key or key in seen:
            continue
        entry = CONTRASTIVE_DB.get(key, {}).get(l2_lang)
        if entry:
            seen.add(key)
            found.append(
                {
                    "l1_word": key,
                    "dangerous": dict(entry["false_friend"]),
                    "safe": dict(entry["true_meaning"]),
                }
            )
    return found


def _summarize_morphology(doc) -> str:
    """Compact morphological highlights (kept lean to avoid prompt-token bloat)."""
    tenses = set()
    for tok in doc:
        if tok.pos_ in ("VERB", "AUX"):
            tenses.update(tok.morph.get("Tense"))
    parts = []
    if tenses:
        parts.append("tense=" + ",".join(sorted(tenses)))
    parts.append(f"nouns={sum(1 for t in doc if t.pos_ == 'NOUN')}")
    return "; ".join(parts)


@mcp.tool()
def analyze_sentence_structure(
    sentence: str, l1_lang: str = "Portuguese", l2_lang: str = "English"
) -> dict:
    """
    Produce a lean structural summary of an L1 sentence for syntactic contrastive analysis.

    Uses spaCy (POS tags + dependency relations + lemmas) when the L1 model is available,
    and always scans for curated false friends embedded in the sentence. Degrades
    gracefully to a whitespace-tokenized, LLM-only payload when no model is installed.

    Returns a dict with keys: input_mode, language, tokens, root, noun_adjective_orders,
    morphology_summary, detected_false_friends, has_local_data, needs_dynamic_suggestions,
    warning.
    """
    text = (sentence or "").strip()
    result = {
        "input_mode": "sentence",
        "language": l1_lang,
        "tokens": [],
        "root": None,
        "noun_adjective_orders": [],
        "morphology_summary": "",
        "detected_false_friends": [],
        "has_local_data": False,
        "needs_dynamic_suggestions": True,
        "warning": None,
    }

    if not text:
        result["warning"] = "Input sentence cannot be empty."
        return result

    nlp, warn = get_model(l1_lang)

    if nlp is None:
        # Graceful degradation: whitespace tokens + curated false-friend scan only.
        raw_tokens = text.split()
        result["tokens"] = [
            {"text": t, "lemma": None, "pos": None, "dep": None, "head": None}
            for t in raw_tokens
        ]
        result["detected_false_friends"] = _scan_false_friends(raw_tokens, l2_lang)
        result["warning"] = warn
        logger.info("mcp.analyze_sentence", extra={"tool": "analyze_sentence_structure",
                    "spacy_loaded": False, "tokens": len(result["tokens"]),
                    "false_friends": len(result["detected_false_friends"])})
        return result

    doc = nlp(text)
    result["has_local_data"] = True
    result["tokens"] = [
        {"text": t.text, "lemma": t.lemma_, "pos": t.pos_, "dep": t.dep_, "head": t.head.text}
        for t in doc
        if not t.is_space
    ]
    roots = [t.text for t in doc if t.dep_ == "ROOT"]
    result["root"] = roots[0] if roots else None
    # Adjective-after-noun occurrences: a classic Romance->English transfer cue.
    result["noun_adjective_orders"] = [
        f"{t.head.text} {t.text}"
        for t in doc
        if t.pos_ == "ADJ" and t.head.pos_ == "NOUN" and t.i > t.head.i
    ]
    result["morphology_summary"] = _summarize_morphology(doc)
    result["detected_false_friends"] = _scan_false_friends([t.text for t in doc], l2_lang)
    logger.info("mcp.analyze_sentence", extra={"tool": "analyze_sentence_structure",
                "spacy_loaded": True, "tokens": len(result["tokens"]),
                "false_friends": len(result["detected_false_friends"])})
    return result


if __name__ == "__main__":
    # Run as a standalone MCP server (stdio transport by default).
    mcp.run()
